### ISSUE TITLE
error during comparison: could not list src tables: could not populate columns: missing destination name COLUMN_NAME in *[]*store.ColumnInfo

### ISSUE THREAD

**Issue by dapieper** [mattermost/dbcmp#2]
Hi,

i'm migrating mattermost from mysql to postgres. I have migrate that data successfully and want to compare the databases with:
`dbcmp --source "${MYSQL_DSN}" --target "${POSTGRES_DSN}" --exclude="db_migrations,ir_,focalboard,systems"`

but i get the error:
`error during comparison: could not list src tables: could not populate columns: missing destination name COLUMN_NAME in *[]*store.ColumnInfo`

MYSQL Version: Percona Server 8.0.29-21
PostgreSQL Version: 14.9

thanks

**Comment by isacikgoz** [comment]
Hey @dapieper we had a few issues with mysql-8. I submitted a couple of fixes, can you try to build again?

**Comment by dapieper** [comment]
Thanks so much. It's working for me now without any errors.
