### ISSUE TITLE
Instructions need more information

### ISSUE THREAD

**Issue by dkeenleyside** [mattermost/dbcmp#6]
Under the "How to use dbcmp" section, the following is mentioned:

`2) To Configure, dbcmp requires access credentials for the databases you want to compare. You can set them directly as command line arguments.`

However, no information is provided as to how this is done, I believe an example is in order.

**Comment by dkeenleyside** [comment]
Example:
`user@mattermost:~/go/bin$ sudo ./dbcmp --source "mmuser:password@tcp(localhost:3306)/mattermost" --target "postgres://mmuser:password@localhost:5432/mattermostdb" --exclude="db_migrations,ir_,focalboard,systems"`

**Comment by isacikgoz** [comment]
Hey @dkeenleyside thanks for raising this. I'm going to add an example to the command help text.
